---
- name: restart consul-snapshot on Linux
  service:
    name: consul_snapshot
    state: restarted
  when: ansible_os_family != "Windows"
  listen: 'restart consul_snapshot'

- name: restart consul-snpashot on windows
  win_service:
    name: consul_snapshot
    state: restarted
  when: ansible_os_family == "Windows"
  listen: 'restart consul_snapshot'
